In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
% matplotlib inline
plt.rcParams['font.sans-serif'] = ['SimHei'] # 显示中文字符
font1 = {'weight' : 'normal','size': 23}
font2 = {'weight' : 'normal','size': 18}
mpl.style.use('ggplot')

In [3]:
train_fd001_path = r'../data/train_FD001.txt'
train_fd001 = pd.read_csv(train_fd001_path,sep=" ", header=None)
train_fd001.drop(train_fd001.columns[[26, 27]], axis=1, inplace=True) #这两列为空，删除
train_fd001.columns = ['id', 'cycle', 'setting1', 'setting2', 'setting3', 's1', 's2', 's3',
                     's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11', 's12', 's13', 's14',
                     's15', 's16', 's17', 's18', 's19', 's20', 's21']

In [4]:
train_fd002_path = r'../data/train_FD002.txt'
train_fd002 = pd.read_csv(train_fd002_path,sep=" ", header=None)
train_fd002.drop(train_fd002.columns[[26, 27]], axis=1, inplace=True) #这两列为空，删除
train_fd002.columns = ['id', 'cycle', 'setting1', 'setting2', 'setting3', 's1', 's2', 's3',
                     's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11', 's12', 's13', 's14',
                     's15', 's16', 's17', 's18', 's19', 's20', 's21']

In [5]:
train_fd003_path = r'../data/train_FD003.txt'
train_fd003 = pd.read_csv(train_fd003_path,sep=" ", header=None)
train_fd003.drop(train_fd003.columns[[26, 27]], axis=1, inplace=True) #这两列为空，删除
train_fd003.columns = ['id', 'cycle', 'setting1', 'setting2', 'setting3', 's1', 's2', 's3',
                     's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11', 's12', 's13', 's14',
                     's15', 's16', 's17', 's18', 's19', 's20', 's21']

In [10]:
train_fd004_path = r'../data/train_FD004.txt'
train_fd004 = pd.read_csv(train_fd004_path,sep=" ", header=None)
train_fd004.drop(train_fd004.columns[[26, 27]], axis=1, inplace=True) #这两列为空，删除
train_fd004.columns = ['id', 'cycle', 'setting1', 'setting2', 'setting3', 's1', 's2', 's3',
                     's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11', 's12', 's13', 's14',
                     's15', 's16', 's17', 's18', 's19', 's20', 's21']

In [16]:
train_all = pd.concat([train_fd001, train_fd002, train_fd003, train_fd004], axis=0)

In [17]:
train_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 160359 entries, 0 to 61248
Data columns (total 26 columns):
id          160359 non-null int64
cycle       160359 non-null int64
setting1    160359 non-null float64
setting2    160359 non-null float64
setting3    160359 non-null float64
s1          160359 non-null float64
s2          160359 non-null float64
s3          160359 non-null float64
s4          160359 non-null float64
s5          160359 non-null float64
s6          160359 non-null float64
s7          160359 non-null float64
s8          160359 non-null float64
s9          160359 non-null float64
s10         160359 non-null float64
s11         160359 non-null float64
s12         160359 non-null float64
s13         160359 non-null float64
s14         160359 non-null float64
s15         160359 non-null float64
s16         160359 non-null float64
s17         160359 non-null int64
s18         160359 non-null int64
s19         160359 non-null float64
s20         160359 non-null float64
s21         160359 non-null float64
dtypes: float64(22), int64(4)
memory usage: 33.0 MB

In [22]:
#显示所有列
pd.set_option('display.max_columns', None)
#显示所有行
pd.set_option('display.max_rows', None)
#设置value的显示长度为100，默认为50
pd.set_option('max_colwidth',100)

train_all.describe()

,id,cycle,setting1,setting2,setting3,s1,s2,s3,s4,s5,s6,s7,s8,s9,s10,s11,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21
count,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000,160359.000000
mean,105.553758,123.331338,17.211973,0.410004,95.724344,485.840890,597.361022,1467.035653,1260.956434,9.894999,14.424935,359.729968,2273.829707,8677.553696,1.153705,44.212049,338.789821,2349.645243,8088.950972,9.054747,0.025185,360.698801,2273.754039,98.389146,25.942709,15.565700
std,72.867325,83.538146,16.527988,0.367938,12.359044,30.420388,42.478516,118.175261,136.300073,4.265554,6.443922,174.133835,142.426613,374.657454,0.142103,3.426342,164.193480,111.167242,80.623257,0.751581,0.004997,31.021430,142.513114,4.656270,11.691422,7.015067
min,1.000000,1.000000,-0.008700,-0.000600,60.000000,445.000000,535.480000,1242.670000,1023.770000,3.910000,5.670000,136.170000,1914.720000,7984.510000,0.930000,36.040000,128.310000,2027.570000,7845.780000,8.156300,0.020000,302.000000,1915.000000,84.930000,10.160000,6.010500
25%,44.000000,57.000000,0.001300,0.000200,100.000000,449.440000,549.960000,1357.360000,1126.830000,5.480000,8.000000,175.710000,2212.120000,8334.770000,1.020000,42.010000,164.790000,2387.970000,8070.530000,8.439250,0.020000,332.000000,2212.000000,100.000000,14.330000,8.601300
50%,89.000000,114.000000,19.998100,0.620000,100.000000,489.050000,605.930000,1492.810000,1271.740000,9.350000,13.660000,341.690000,2319.370000,8764.200000,1.090000,44.930000,321.690000,2388.070000,8118.590000,9.030100,0.030000,367.000000,2319.000000,100.000000,24.920000,14.953500
75%,164.000000,173.000000,35.001500,0.840000,100.000000,518.670000,642.340000,1586.590000,1402.200000,14.620000,21.610000,553.290000,2388.050000,9055.850000,1.300000,47.340000,521.340000,2388.160000,8139.410000,9.344200,0.030000,392.000000,2388.000000,100.000000,38.820000,23.294600
max,260.000000,543.000000,42.008000,0.842000,100.000000,518.670000,645.110000,1616.910000,1441.490000,14.620000,21.610000,570.810000,2388.640000,9244.590000,1.320000,48.530000,537.490000,2390.490000,8293.720000,11.066900,0.030000,400.000000,2388.000000,100.000000,39.890000,23.950500